name: "minecraft-server"
services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    ports:
      - "25565:25565"  # Minecraft server port
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      MEMORY: "4G"
      # SEED
      # from https://beebom.com/best-minecraft-seeds/ -> 2. Three Villages and a Cherry Grove
      # Spawn at village
      SEED: "5348024562502568"
      SPAWN: "-34,122,-26"
      # Admin users
      OPS: |
        DeKuen
        Kagemono
      # RCON for backup script
      ENABLE_RCON: "true"
      RCON_PASSWORD: "change_me"
    volumes:
      - ./data:/data                               # Bind mount for real files on disk
      - ./mods:/mods:ro
    restart: unless-stopped
