name: "minecraft-server"
services:
  minecraft-server:
    image: itzg/minecraft-server:latest
    container_name: minecraft-paper
    ports:
      - "25565:25565"  # Minecraft server port
      - "8123:8123"    # Dynmap's default web port
      - "5005:5005"    # Java debug port
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.4"
      MEMORY: "2G"
      # SEED
      # from https://beebom.com/best-minecraft-seeds/ -> 2. Three Villages and a Cherry Grove
      # Spawn at village
      SEED: "5348024562502568"
      SPAWN: "-34,122,-26"
      # list of plugins to install
      PLUGINS_FILE: /extras/plugins.txt
      # Admin users
      OPS: |
        DeKuen
      # RCON for backup script
      ENABLE_RCON: "true"
      RCON_PASSWORD: "change_me"
      # resource pack for custom sounds
      RESOURCE_PACK: "https://github.com/Wuodan/humorous-mc-plugin/releases/download/1.10-alpha-4/fartpack.zip"
      RESOURCE_PACK_ID: "001c1a9e-5b85-4e0b-a141-9f44a7d945d7"
      RESOURCE_PACK_PROMPT: '{"text":"Do you want to install custom fart sounds?"}'
      RESOURCE_PACK_SHA1: "a5d9c00b48d1f2a8c47d226c8caa5b7e6d26f948"
      # use this together with the patch_definitions volume as alternative to overwriting SneakFart config.yml
      # PATCH_DEFINITIONS: /data/patch_definitions
    volumes:
      - ./data:/data                               # Bind mount for real files on disk
      - ./plugins.txt:/extras/plugins.txt:ro       # list of plugins to install
      - ./SneakFart-config.yml:/data/plugins/SneakFart/config.yml:ro
#      - ./patch_definitions:/data/patch_definitions:ro
    restart: unless-stopped
